library(qtl)
library(snow)
library(rlecuyer)
data <- read.cross("csv", ".", "rQTL_May_SNP_stacked_5_2_13.csv")
class(data)[1]="riself"
data<-jittermap(data)
cyto_block<-read.csv(file="block_cyto_treatment.csv", header=TRUE)
block1<-as.vector(cyto_block$block1)
block2<-as.vector(cyto_block$block2)
block3<-as.vector(cyto_block$block3)
block4<-as.vector(cyto_block$block4)
block5<-as.vector(cyto_block$block5)
cyto<-as.vector(cyto_block$cyto)
treatment<-as.vector(cyto_block$treatment)
x<-cbind(block1, block2, block3, block4, block5, cyto, treatment)
dataIM<-calc.genoprob(data, step=1, map.function="kosambi")


out.a=scanone(dataIM, pheno.col=1:2500, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=1:2500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=1:2500, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=1:2500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_2500<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_2500, file = "Tab_by_SNP_treatment_2500.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=2501:5000, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=2501:5000, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=2501:5000, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=2501:5000, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_5000<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_5000, file = "Tab_by_SNP_treatment_5000.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=5001:7500, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=5001:7500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=5001:7500, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=5001:7500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_7500<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_7500, file = "Tab_by_SNP_treatment_7500.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=7501:10000, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=7501:10000, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=7501:10000, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=7501:10000, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_10000<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_10000, file = "Tab_by_SNP_treatment_10000.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=10001:12500, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=10001:12500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=10001:12500, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=10001:12500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_12500<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_12500, file = "Tab_by_SNP_treatment_12500.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=12501:15000, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=12501:15000, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=12501:15000, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=12501:15000, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_15000<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_15000, file = "Tab_by_SNP_treatment_15000.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=15001:17500, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=15001:17500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=15001:17500, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=15001:17500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_17500<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_17500, file = "Tab_by_SNP_treatment_17500.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=17501:20000, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=17501:20000, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=17501:20000, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=17501:20000, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_20000<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_20000, file = "Tab_by_SNP_treatment_20000.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=20001:22500, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=20001:22500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=20001:22500, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=20001:22500, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_22500<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_22500, file = "Tab_by_SNP_treatment_22500.txt", quote=FALSE, row.name=FALSE)

out.a=scanone(dataIM, pheno.col=22501:25662, addcov=x, model=c("normal"), method=c("hk"))
out.u=scanone(dataIM, pheno.col=22501:25662, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"))
set.seed(54955149)
operm.a <- scanone(dataIM, pheno.col=22501:25662, addcov=x, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
set.seed(54955149)
operm.u <- scanone(dataIM, pheno.col=22501:25662, addcov=x, intcovar=treatment, model=c("normal"), method=c("hk"), n.perm=1000, n.cluster=6)
out.u <- c(out.u, out.u-out.a, labels=c("f","i"))
operm.u <- cbind(operm.u, operm.u - operm.a, labels=c("f","i"))
tabbycol_25662<-summary(out.u, perms=operm.u, format="tabByCol", pvalues=TRUE, ci.function="lodint")

write.table(tabbycol_25662, file = "Tab_by_SNP_treatment_25662.txt", quote=FALSE, row.name=FALSE)
